[package]
name = "picman"
version = "0.1.0"
authors = ["Lewis Gunsch <lgunsch@gmail.com>"]

[dependencies]
docopt = "~0"
log = "~0"
regex = "~0"
rust-crypto = "0.2.31"
rustc-serialize = "~0"
walker = "^1.0.0"

[dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"
