[package]
name = "picman"
version = "0.0.1"
authors = ["Lewis Gunsch <lgunsch@gmail.com>"]

[dependencies]
regex = "~0"
walker = "^1.0.0"
docopt = "~0"
rustc-serialize = "~0"

[dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"
